# Generated by Django 4.2.1 on 2023-07-02 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('andyverseapi', '0002_alter_customuser_managers_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FutureReviews',
        ),
    ]
