# Generated by Django 4.2.1 on 2023-07-09 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andyverseapi', '0004_andyverseuser_moviereview_movie_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviereview',
            name='author',
        ),
        migrations.AddField(
            model_name='moviereview',
            name='author_uid',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='moviereview',
            name='is_movie',
            field=models.BooleanField(default=True),
        ),
    ]
