# Generated by Django 4.2.1 on 2023-07-10 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andyverseapi', '0005_remove_moviereview_author_moviereview_author_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviereview',
            name='movie_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
