# Generated by Django 4.2.1 on 2023-07-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andyverseapi', '0006_alter_moviereview_movie_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviereview',
            name='review_summary',
            field=models.CharField(default='FUTURE', max_length=255),
        ),
    ]
