# Generated by Django 4.2.1 on 2023-07-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andyverseapi', '0008_moviereview_author_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_email', models.TextField(max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('status', models.CharField(default='unread', max_length=20)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('suggestion', 'Suggestion'), ('contact', 'Contact')], max_length=20)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date_sent'],
            },
        ),
    ]
