# Generated by Django 4.2.1 on 2023-07-23 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andyverseapi', '0009_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender_email',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
