version: '4.19'

services:
  django_gunicorn:
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - static:/static
    env_file:
      - .env
    build:
      context: ''
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443" #HTTPS
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - static:/static
    depends_on:
      - django_gunicorn

volumes:
  static:
